cors:
  originPatterns: "*"
file:
  upload-dir: uploads
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  profiles:
    active: local
  application:
    name: sistema-controle-documental
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_controle_documental
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB     # Tamanho máximo de um único arquivo
      max-request-size: 10MB  # Tamanho máximo da requisição inteira
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
logging:
  level:
    br.com.barbara.sistema_controle_documental: DEBUG